### ISSUE TITLE
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY 

### ISSUE THREAD

**Issue by Svancara** [ArtS/aws-retrieve-secret#1]
Excuse me, but you wrote the goal is to not store credentials in config files 
> if you just want to ward off people that are not supposed to be poking around and sticking their noses into everything,

So we suppose someone got access to the computer where those config files are available.

Having AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in environment variables is even much WORSE problem than the original one! Because the same poking guy can get them from the environment easily and he has open doors to the whole AWS account! 

Correct?

**Comment by ArtS** [comment]
Generally speaking this is the way AWS credentials work -- see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

Most of the time it's not a problem because in AWS environment instances are deployed in a secure way with their configs / env vars set during the creation, and only accessible via ssh/remote desktop to someone with admin rights / PEM key.
